"""Quick benchmark: drag minimisation of an axisymmetric Sears-Haack body at M = 1.8 (Euler).

SU2 8.5 with AXISYMMETRIC= YES and the discrete adjoint; FFD box 27 x 2 (Bernstein), 25 design variables =
radial displacements of the upper row (end points and the axis row frozen -> length fixed);
constraints: volume >= baseline volume, |dr| <= 0.3 R_max; SciPy SLSQP.
Before the optimisation the adjoint gradient is compared with central finite differences on two variables.

Usage (from the repository root):
    SU2_NP=4 python scripts/bench_axi.py --workdir runs/axi --maxiter 30      # ~10 min on 6 cores
    SU2_NP=2 python scripts/bench_axi.py --workdir runs/axi_smoke --maxiter 2  # smoke test, ~4 min on 2 cores
The mesh (~25k triangles) is generated with gmsh on the first run.
"""
import argparse
import json
import os
import shutil
import sys
import time
from math import comb

import numpy as np
from scipy.optimize import minimize

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import su2run as S  # noqa: E402
import bench_axi_mesh as BM_  # noqa: E402

TEMPLATE = os.path.join(S.REPO, "config", "sears_haack_axi.cfg")
RMAX = BM_.R_MAX
FFD = dict(x=(-0.005, 1.005), y=(0.0, 0.11), deg=26)
IDV = list(range(1, FFD["deg"]))          # i = 1..25, j = 1, y (radial) displacement; i = 0 and 26 frozen
NDV = len(IDV)


def cfg(path, **kw):
    x = kw.pop("x", np.zeros(NDV))
    d = dict(MATH="DIRECT", RESTART="NO", AREF=f"{np.pi * RMAX**2:.8f}", CONVF="RMS_DENSITY", MINVAL="-12",
             X0=FFD["x"][0], X1=FFD["x"][1], Y1=FFD["y"][1], DEG=FFD["deg"], MESH="../sh_axi_ffd.su2",
             SOL="solution_flow.dat", VTU="", HIST="(ITER, RMS_RES, AERO_COEFF)",
             DVK=", ".join(["FFD_CONTROL_POINT_2D"] * NDV),
             DVP="; ".join(f"( BOX, {i}, 1, 0.0, 1.0 )" for i in IDV),
             DVV=", ".join(f"{v:.10g}" for v in x))
    d.update(kw)
    S.fill_template(TEMPLATE, d, path)


class Body:
    """Body contour from the mesh, the FFD map (same Bernstein formula as SU2) and the exact volume of the
    body of revolution generated by the polyline contour."""

    def __init__(self, mesh):
        lines = open(mesh).read().splitlines()
        i = next(n for n, l in enumerate(lines) if l.startswith("NPOIN"))
        npo = int(lines[i].split("=")[1].split()[0])
        self.xy0 = np.array([[float(v) for v in lines[i + 1 + p].split()[:2]] for p in range(npo)])
        j = next(n for n, l in enumerate(lines) if l.strip() == "MARKER_TAG= body")
        ne = int(lines[j + 1].split("=")[1])
        self.seg = np.array([[int(v) for v in lines[j + 2 + e].split()[1:3]] for e in range(ne)])
        xy = self.xy0
        U = (xy[:, 0] - FFD["x"][0]) / (FFD["x"][1] - FFD["x"][0])
        Vv = xy[:, 1] / FFD["y"][1]
        n = FFD["deg"]
        self.B = np.array([comb(n, i) * U**i * (1 - U) ** (n - i) * Vv for i in IDV]).T     # j = 1 -> factor v
        self.B[(xy[:, 1] > FFD["y"][1]) | (xy[:, 0] < FFD["x"][0]) | (xy[:, 0] > FFD["x"][1])] = 0.0
        self.V0 = self.volume(np.zeros(NDV))

    def radius(self, x):
        return self.xy0[:, 1] + self.B @ x

    def volume(self, x):
        y, x_ = self.radius(x), self.xy0[:, 0]
        a, b = self.seg[:, 0], self.seg[:, 1]
        return abs(np.sum(np.pi * (x_[b] - x_[a]) * (y[a] ** 2 + y[a] * y[b] + y[b] ** 2) / 3.0))

    def dvolume(self, x, h=1e-7):
        g = np.zeros(NDV)
        for k in range(NDV):
            e = np.zeros(NDV); e[k] = h
            g[k] = (self.volume(x + e) - self.volume(x - e)) / (2 * h)
        return g


class Ev:
    def __init__(self, wd, body):
        self.wd, self.body, self.cache, self.n, self.base = wd, body, [], 0, None
        self.log = os.path.join(wd, "history_opt.csv")
        open(self.log, "w").write("eval,time_s,CD,V_rel,max_abs_dv_R,rho0,rho_end,has_grad\n")
        self.t0 = time.time()

    def primal(self, x):
        x = np.array(x, float, copy=True)
        for c in self.cache:
            if np.allclose(c["x"], x, atol=1e-13, rtol=0):
                return c
        d = os.path.join(self.wd, f"e_{self.n:03d}")
        os.makedirs(d, exist_ok=True)
        mesh = "../sh_axi_ffd.su2"
        if np.any(x != 0):
            cfg(os.path.join(d, "def.cfg"), x=x)
            S.run("SU2_DEF", "def.cfg", d, "log_def.txt")
            mesh = "mesh_def.su2"
        cfg(os.path.join(d, "direct.cfg"), x=x, MESH=mesh, RESTART="YES" if self.base else "NO",
            SOL=self.base or "solution_flow.dat", VTU=", PARAVIEW")
        S.run("SU2_CFD", "direct.cfg", d, "log_direct.txt")
        hdr, a = S.read_history(os.path.join(d, "history.csv"))
        r = dict(x=x, d=d, mesh=mesh, n=self.n, CD=a[-1, hdr.index("CD")], rho0=a[0, hdr.index("rms[Rho]")],
                 rho_end=a[-1, hdr.index("rms[Rho]")], V=self.body.volume(x))
        if self.base is None:
            self.base = f"../e_{self.n:03d}/restart_flow.dat"
        self.cache.append(r)
        self.n += 1
        with open(self.log, "a") as f:
            f.write(f"{r['n']},{time.time() - self.t0:.0f},{r['CD']:.8f},{r['V'] / self.body.V0:.6f},"
                    f"{np.abs(x).max() / RMAX:.4f},{r['rho0']:.3f},{r['rho_end']:.3f},0\n")
        print(f"[{r['n']:3d}] CD={r['CD']:.6f} V/V0={r['V'] / self.body.V0:.5f} "
              f"rho={r['rho_end']:.1f} t={time.time() - self.t0:.0f}s", flush=True)
        return r

    def grad(self, x):
        r = self.primal(x)
        if "g" in r:
            return r
        d = r["d"]
        cfg(os.path.join(d, "adj.cfg"), x=r["x"], MESH=r["mesh"], MATH="DISCRETE_ADJOINT", SOL="restart_flow.dat",
            CONVF="RMS_ADJ_DENSITY", MINVAL="-11", HIST="(ITER, RMS_RES, SENSITIVITY)")
        S.run("SU2_CFD_AD", "adj.cfg", d, "log_adj.txt")
        shutil.copy(os.path.join(d, "restart_adj_cd.dat"), os.path.join(d, "solution_adj_cd.dat"))
        S.run("SU2_DOT_AD", "adj.cfg", d, "log_dot.txt")
        r["g"] = S.read_grad(os.path.join(d, "of_grad.csv"))
        np.savetxt(os.path.join(d, "grad_CD.txt"), r["g"])
        return r


def setup(wd, h_mesh=0.003):
    """Mesh + FFD box embedded into it (SU2_DEF with FFD_SETTING)."""
    os.makedirs(wd, exist_ok=True)
    S.TIMING_CSV = os.path.join(wd, "timing.csv")
    if not os.path.exists(os.path.join(wd, "sh_axi.su2")):
        BM_.make_mesh(os.path.join(wd, "sh_axi.su2"), h_mesh)
    if not os.path.exists(os.path.join(wd, "sh_axi_ffd.su2")):
        cfg(os.path.join(wd, "ffd.cfg"), MESH="sh_axi.su2", DVK="FFD_SETTING", DVP="( BOX, 1.0 )", DVV="0.0")
        t = open(os.path.join(wd, "ffd.cfg")).read().replace("MESH_OUT_FILENAME= mesh_def.su2",
                                                               "MESH_OUT_FILENAME= sh_axi_ffd.su2")
        open(os.path.join(wd, "ffd.cfg"), "w").write(t)
        S.run("SU2_DEF", "ffd.cfg", wd, "log_ffd.txt", 1)
    return Body(os.path.join(wd, "sh_axi.su2"))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workdir", default="runs/axi")
    ap.add_argument("--maxiter", type=int, default=30)
    ap.add_argument("--h-mesh", type=float, default=0.003)
    ap.add_argument("--skip-fd", action="store_true", help="skip the finite-difference gradient check")
    a = ap.parse_args()
    S.check_su2()
    wd = os.path.abspath(a.workdir)
    body = setup(wd, a.h_mesh)
    E = Ev(wd, body)
    x0 = np.zeros(NDV)
    r0 = E.grad(x0)
    chk = []
    if not a.skip_fd:
        h = 0.02 * RMAX
        for k in np.argsort(-np.abs(r0["g"]))[:2]:
            e = np.zeros(NDV); e[k] = h
            fd = (E.primal(x0 + e)["CD"] - E.primal(x0 - e)["CD"]) / (2 * h)
            chk.append(dict(dv=int(IDV[k]), adjoint=float(r0["g"][k]), fd=float(fd),
                            rel_err=float(abs(fd - r0["g"][k]) / abs(fd))))
            print("gradient check (adjoint vs central FD):", chk[-1], flush=True)
    res = minimize(lambda x: 1e3 * E.primal(x)["CD"], x0, jac=lambda x: 1e3 * E.grad(x)["g"], method="SLSQP",
                   bounds=[(-0.3 * RMAX, 0.3 * RMAX)] * NDV,
                   constraints=[dict(type="ineq", fun=lambda x: 100 * (body.volume(x) / body.V0 - 1.0),
                                     jac=lambda x: 100 * body.dvolume(x) / body.V0)],
                   options=dict(maxiter=a.maxiter, ftol=1e-7, disp=True))
    rf = E.primal(res.x)
    out = dict(CD0=r0["CD"], CD_opt=rf["CD"], dCD_pct=100 * (rf["CD"] / r0["CD"] - 1), V_rel=rf["V"] / body.V0,
               nit=int(res.nit), nfev=E.n, msg=res.message, final_eval=rf["n"], grad_check=chk,
               elapsed_s=time.time() - E.t0)
    json.dump(out, open(os.path.join(wd, "result.json"), "w"), indent=1)
    np.savetxt(os.path.join(wd, "x_opt.txt"), res.x)
    print(json.dumps(out, indent=1))


if __name__ == "__main__":
    main()
